export const CONTACT_LEGAL_LOADING = 'CONTACT_LEGAL_LOADING';
export const GET_LEGAL = 'GET_LEGAL';
export const CONTACT_LEGAL_ERROR = 'CONTACT_LEGAL_ERROR';
export const CONTACT_LEGAL_RESET = 'CONTACT_LEGAL_RESET';
export const CONTACT_LEGAL_SUCCESS = 'CONTACT_LEGAL_SUCCESS';
