name: Docker Image CI

on:
  push:
    branches: [devOps-setup]
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag constitution-browser:$(date +%s)
